language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  slack: jamesj0717:$SLACK_TOKEN
node_js:
  - "10"
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  fqdn: https://www.jamesjohnson.io
  target-branch: master
  on:
    branch: dev
