version: "3.5"

services:
  personal-site:
    image: personal-site
    build: .
    environment:
      NODE_ENV: production
    labels:
      - traefik.enable=true
      - traefik.http.routers.me.rule=Host(`www.jamesjohnson.io`)
      - traefik.http.routers.me.entrypoints=web
      - traefik.http.routers.me.middlewares=redirect@file
      - traefik.http.routers.me-https.rule=Host(`www.jamesjohnson.io`)
      - traefik.http.routers.me-https.entrypoints=websecure
      - traefik.http.routers.me-https.tls=true
    networks:
      - web
networks:
  web:
    external: true
