# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
      
  deploy:
    docker:
      - image: circleci/node
      
    steps: 
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install GH_Pages
          command: |
            npm install -g --silent gh-pages
            git config user.email me@jamesjohnson.io
            git config user.name  "James Johnson"
      - add_ssh_keys:
          fingerprints:
            - "9f:a1:11:79:24:ac:47:bd:6f:b1:90:32:4d:49:94:81"
      - run:
          name: Deploy to GH_Pages
          command: gh-pages --dist ~/repo/build --branch master
          
