# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
  deploy:
    docker:
      - image: node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run:
          name: Install GH_Pages
          command: |
            npm install -g gh-pages
            git config user.email me@jamesjohnson.io
            git config user.name "James Johnson"
      - add_ssh_keys:
          fingerprints:
            - "9f:a1:11:79:24:ac:47:bd:6f:b1:90:32:4d:49:94:81"
      - run:
          name: Deploy to GH_Pages
          command: gh-pages -d public --message "[ci skip] deploy"

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: dev
  buildDeploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
